services:
  isaac-tracker:
    image: maxijabase/isaac-tracker:latest
    container_name: isaac-tracker
    restart: unless-stopped
    ports:
      - "3020:80"
    environment:
      - PUBLIC_URI=https://isaac.maxijabase.dev/
    volumes:
      - isaac-cache:/tmp/steam-cache

volumes:
  isaac-cache:
